development:
  adapter: postgresql
  encoding: unicode
  database: round_trip_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: round_trip_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: round_trip_production
  pool: 5
  username:
  password:
